
export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";
export const SET_SUCCESS = "SET_SUCCESS";

export const GET_SEARCH_SUCESS = "GET_SEARCH_SUCCESS";
export const GET_IMG_ANALYSIS_SUCCESS = "GET_IMG_ANALYSIS_SUCCESS";
export const GET_MEAL_PLAN_SUCCESS = "GET_MEAL_PLAN_SUCCESS";

export const GET_IMG_ANALYSIS_DETAILS_SUCCESS = "GET_IMG_ANALYSIS_DETAILS_SUCCESS";
export const GET_MEAL_PLAN_DETAILS_SUCCESS = "GET_MEAL_PLAN_DETAILS_SUCCESS";
